### ISSUE TITLE
In raw thumbnail of crop windows is LARGE size

### ISSUE THREAD

**Issue by 1ucay** [vollyimnetz/crop-thumbnails#100]
Hi, if I upload image with 3024 x 4032 pixel and have code below, in thumbnail of crop windows is LARGE size. I think that changing sizes of large and medium was bad idea. Can you please add filter to change size in modal window? I just add "full" size instead "large". Thank you.

    add_filter( 'pre_option_medium_large_size_h', 'default_image_options' );
    add_filter( 'pre_option_medium_large_size_w', 'default_image_options' );
    add_filter( 'pre_option_medium_large_crop', function() { return array( 'center', 'center' ); } );
    function default_image_options( $value ) {

        $option = str_replace( 'pre_option_', '', current_filter() );

        switch ( $option ) {

            case 'thumbnail_size_w' :
                $value = 150;
                break;
            case 'thumbnail_size_h' :
                $value = 150;
                break;

            case 'medium_size_w' :
                $value = 768;
                break;
            case 'medium_size_h' :
                $value = 512;
                break;

            case 'medium_large_size_w' :
                $value = 1152;
                break;
            case 'medium_large_size_h' :
                $value = 768;
                break;

            case 'large_size_w' :
                $value = 1920;
                break;
            case 'large_size_h' :
                $value = 1280;
                break;
        }

        return $value;
    }

**Comment by vollyimnetz** [comment]
Can you please a little further what the intention of your code is? I do not understand.

**Comment by vollyimnetz** [comment]
Please download an use the latest code from the master. You may have a look at: https://github.com/vollyimnetz/crop-thumbnails?tab=readme-ov-file#filter-crop_thumbnails_crop_data how to adjust the crop-area-background-image.

Please let me know if this fixes your two errors, so i can release the new version.

**Comment by 1ucay** [comment]
Nice, thank you. Working good for me with this filter and master branch.

**Comment by vollyimnetz** [comment]
Live in version 1.9.5
