### ISSUE TITLE
No refresh after cropping the post thumbnail

### ISSUE THREAD

**Issue by sebastianroming** [vollyimnetz/crop-thumbnails#12]
I'm using this plugin mostly for post thumbnails, but now i want the article image to refresh after beeing cropped. If i save the post, the thumbnail is saved correctly and the page displays the correct size.
But if I reopen the edit page, the original thumbnail is shown in the meta-box and the user has to assume that he has to re-crop the image.

In the `readme.txt` you wrote something like
```
$('body').on('cropThumbnailModalClosed',function() {
	CROP_THUMBNAILS_DO_CACHE_BREAK( $('.your-image-selector') );
});
```

But this won't help me as I won't touch the wordpress core code. Is there any other possibility?

**Comment by vollyimnetz** [comment]
Hi you won't change the wordpress core code. These Change will only effect the backend via Javascript.
If you want a cachebreaker on every load on the edit-page you may use the following code.

`
add_action('admin_footer', 'addCropThumbnailCacheBreakToAdminFooter',9999);
function addCropThumbnailCacheBreakToAdminFooter() {
	?>
	<script>
	jQuery(document).ready(function($) {
		CROP_THUMBNAILS_DO_CACHE_BREAK( $('#postimagediv img') );
	});
	</script>
	<?php
}
`

A note: please use the support forum on wordpress.org for support questions. GitHub is for development issues.
