### ISSUE TITLE
Wrong overflow on iOS Safari

### ISSUE THREAD

**Issue by LucaPipolo** [vollyimnetz/crop-thumbnails#13]
**Problem:**
- Using iOS Safari (both from iPad and iPhone) is not possible to see all the crop options since iframe overflow is hidden as default behavior;

**Possible solution**
- Set `style="overflow-y: scroll; -webkit-overflow-scrolling: touch;"` as attributes of `<html>` element in `html/template.php` to override the default iOS Safari behavior.

**Comment by sun** [comment]
We were still discovering this issue even after upgrading to iOS 9.3.5.

**Comment by vollyimnetz** [comment]
Hi Luca, i check your pull-request. Thanks for contributing.

The problem is: the plugin has bigger problemes on ios. The crop do not work on ipad. I will investigate in the next days to get better touch support.

As sun noticed, the single line do not fix the modal scroll problem on the current iOS

**Comment by LucaPipolo** [comment]
@vollyimnetz — I think that @sun was talking about "how/when we discover" the issue for the first time. The PR fix the modal scroll problem as well on iOS 10.2.

However really thanks for your quick feedback. We'll wait for further update: great to know that you're planning to improve the whole touch support.

**Comment by vollyimnetz** [comment]
Hi @LucaPipolo and @sun,
i refactored the modal-dialog and switch to another crop-library. Please have a look at:
https://github.com/vollyimnetz/crop-thumbnails/tree/touch-improvements

Could you test it and report if you experience any issues?

**Comment by LucaPipolo** [comment]
@vollyimnetz — of course! I'm installing it on some test websites. Let you know in a while. 
Thanks for the help!

**Comment by vollyimnetz** [comment]
I noticed two problemes:
- after cropping the crop area get lost (on ipad)
- with large images the crop-library got some Problemes (cause it working on the original image)

**Comment by vollyimnetz** [comment]
With version 1.0 i implemented a new responsive design and also changed the js-crop-library to be more stable.
