### ISSUE TITLE
Preview doesn't show on, so it's not possible to select the picture for cropping

### ISSUE THREAD

**Issue by funkycram** [vollyimnetz/crop-thumbnails#19]
When cropping a featured image (in the gallery it works, the problem occur in an article, for the featured image), the preview picture on the right side doesn't show.
So it is not possible to select the image making crop not possible.

This problem is new, but I cannot tell what version made the problem happen. No modifications of my website has been done, only updates.

See this screenshot :
![image](https://user-images.githubusercontent.com/23310825/30542411-9bde0a62-9c7f-11e7-842e-d0670075321f.png)

Version : 0.10.15
Wordpress : 4.8.1

Thanks

**Comment by vollyimnetz** [comment]
Will be answered on https://wordpress.org/support/topic/preview-doesnt-show-on-so-its-not-possible-to-select-the-picture-for-cropping

**Comment by funkycram** [comment]
Fine, thanks !
