### ISSUE TITLE
Custom crops not created + code notice / error

### ISSUE THREAD

**Issue by xoref** [vollyimnetz/crop-thumbnails#22]
We use this plugin for our crops, but after the update to v1.0 cropping started to fail, I've done some debugging and found that:
1. When you change the image size name via the `image_size_names_choose` filter, the new cropper sends this customized image size title, instead of the image size name(slug) as the `name` param to the wp-ajax action `crop_thumbnails`. This causes a mismatch which fails to crop the selected image.
**Example Ajax json-value**:
`{"selection":{"x":124.72647702407001,"y":0,"x2":457.33041575492337,"y2":333,"w":332.6039387308534,"h":333},"sourceImageId":91710,"activeImageSizes":[{"name":"thumbnail","width":150,"height":150,"ratio":1,"crop":true},{"name":"Square (1:1)","width":500,"height":500,"ratio":1,"crop":true},{"name":"Logo Thumb (1:1)","width":75,"height":75,"ratio":1,"crop":true}]}`
Notice the `Square (1:1)` and `Logo Thumb` values, which should have been `img-square` & `img-thumb`

2. The `GetCropData()` method in the `CropPostThumbnailsEditor` class (editor:#108) uses a non-existing variable `$current_parent_post_type`:
`$result['hiddenOnPostType'] = self::shouldBeHiddenOnPostType($options,$current_parent_post_type);`

**Comment by vollyimnetz** [comment]
hi there,
new release is on the way:
https://github.com/vollyimnetz/crop-thumbnails/releases/tag/1.1.0
