### ISSUE TITLE
Retina / Hi-Res / HiDPI Image Sizes

### ISSUE THREAD

**Issue by zitrusblau** [vollyimnetz/crop-thumbnails#25]
Hey,

first of all: Your plugin really makes a difference as it's really a much more userfriendly solution than other plugins out there, thanks!

I wonder what would be a good strategy to handle retina sizes image versions.
When adding image sizes with @2x suffixes, the plugin will list them for cropping.

so far, so good.
but when using more image sizes, the UI might get crowded with a lot of image sizes to handle.

sure, it will automatically select image sizes with the same aspect ratio but still, this doesn't tidy up the screen.

i tried to hide those image sizes by using 
`add_filter( 'crop_thumbnails_image_sizes', function($sizes) {
  $sizes = array_filter($sizes, function($size) {
    return (strpos($size['id'], '@2x') === false);
  });

  return $sizes;
});`

but then, the related retina image sizes are no longer cropped automatically which will yield to unwanted results when displaying the retina images.

what do you think of having the possibility to automatically crop those retina sizes even though they are hidden (by a different filter maybe).

but even if this would work, what happens if those retina sizes are hidden and won't still get cropped if the size of the original uploaded image is not big enough to create the retina version. Maybe this is not a problem your plugin needs to handle but rather a general WP issue...

**Comment by zitrusblau** [comment]
Thanks for your follow-up.

I feel adding a filter hook for this purpose might be a more robust solution. Adding CSS-classes is not a bad idea either. Hiding them via CSS would be ok i guess.

But why not hiding retina image sizes by default (and let the user decide by setting or filter hook, if they should be shown)? From a user perspective, this seems to make more sense, doesn't it?

**Comment by zitrusblau** [comment]
ok, i see.
using the action "crop_thumbnails_after_save_new_thumb" could be a starting point. but we would need the cropping details from the cropped image and then trigger the method for cropping the retina image.

maybe using CSS classes is the way to go, at least for now ;)

**Comment by vollyimnetz** [comment]
I added css-classes to the listing in version 1.1.2
