### ISSUE TITLE
Is it possible to force the use of Imagemagick?

### ISSUE THREAD

**Issue by justanotherco** [vollyimnetz/crop-thumbnails#26]
Fantastic plugin!

But on my server I use ImageMagick and use this plugin to force WordPress to use it:
https://wordpress.org/plugins/imagemagick-engine/

However, when I re-crop the images with your plugin, the images lose quality.

Is there a way to make your plugin use ImageMagick? This way the images look better for the same file size.

**Comment by vollyimnetz** [comment]
If wordpress is using imagemagick, then my plugin do so to. The plugin uses the standard wordpress functions for scaling and cropping. Please use the "plugin check" on the settings screen of my plugin. It will show you what image-library is used for cropping.
