### ISSUE TITLE
Check capabilities

### ISSUE THREAD

**Issue by zitrusblau** [vollyimnetz/crop-thumbnails#27]
Might be cool to check for the capability "edit_others_attachments" in order to check for providing the crop feature or not.
We have a scenario where authors might choose images from the media library but are not allowed to edit them further (strange, but hey). Now, they are still able to crop the images nonetheless.

**Comment by zitrusblau** [comment]
A filter hook might be good as well

**Comment by vollyimnetz** [comment]
Yeah, you are right - would be good if this gets more precise.

I will have a look at it - but i currently very busy.

**Comment by zitrusblau** [comment]
cool, thanks

**Comment by vollyimnetz** [comment]
OK, this will be in the next release (1.2.0).
I checked the capabilities but there is no "edit_others_attachments" capability. Only the "edit_files" and "upload_files" capibility.

So starting from version 1.2 you are able to configure in the settings to only allow users how has the privilege to "edit_files". Alternately you can use a filter (crop_thumbnails_user_permission_check) to have some custom right-management - have a look at the readme.
