### ISSUE TITLE
Featured Thumbnail is not displayed

### ISSUE THREAD

**Issue by Keomoniroath** [vollyimnetz/crop-thumbnails#29]
Great plugin but when I cropped an image the featured thumbnail in the post edit page is not displayed.
I also use the plugin "related post" which use the thumbnail size for related posts.
Version : 1.2.2 
Wordpress : 4.9.8

A screen :
![image](https://user-images.githubusercontent.com/29626942/50212764-200c0f00-037c-11e9-8ac9-c2f83622396f.png)

**Comment by vollyimnetz** [comment]
hi Keomoniroath,
i cant reproduce this. Can you please post system informations:
- php version
- wordpress version
- do you use gutenberg or classic editor?
- do the problem persist when only crop thumbnails is active?
- is there an Javascript error in your browsers developer console?

**Comment by Keomoniroath** [comment]
Hi vollyimnetz,

Thank you for your answer. The problem persist when only crop thumbnails is active and we have no JS error in the console.
For information we use the plugin Microsoft Azure Storage for hosting our media. You can have an exemple at the bottom of the post in the section "Découvrez également" : https://experiences.microsoft.fr/business/new-culture-of-work-business/linnovation-appelle-un-equilibre-entre-ambition-et-humilite-nicolas-marry-avanade/

Once the image is cropped, the srcset url change to "https://experiences.microsoft.fr/wp-content/uploads/..."
and it should be "https://experienceswp.blob.core.windows.net/uploads/..."

Below the system informations:
PHP 7
Wordpress : 4.9.8
Classis editor

**Comment by vollyimnetz** [comment]
Hi there, sorry for responding so slow.
I asume that the cloud storage is indeed a problem. My plugin will store the image in the default directory. If the Storage plugin do not sync after crop, then the cropped version will not be visible in frontend (do the image change in frontend?). The visibility of the backend may also up to the CDN-storage-plugin.

You may use one of the actions/hook from my plugin, to start the sync of the CDN-Plugin right after cropping/saving. Have a look at the readme for more details.
