### ISSUE TITLE
Crop functionality not working on taxonomy edit pages

### ISSUE THREAD

**Issue by jonbp** [vollyimnetz/crop-thumbnails#30]
The crop functionality doesn't seem to be working on taxonomy edit pages.

WooCommerce has thumbnails that use could this functionality and in my use case, i have ACF image fields on taxonomies.

I managed to resolve this by adding `'term.php'` to the `$result` filter in the `shouldCropThumbnailsBeActive()` function of `backendpreparer.php`.

I'm not sure if this is the extent of the fix but it seems to work...

**Comment by jonbp** [comment]
I'm sorry.... I jumped the gun, just read the comment and this seems to be intentional.

**Comment by vollyimnetz** [comment]
Hi jonbp,
yes its intensional - cause cropping images are normaly not needed in Taxonomy. But as you might have seen the readme of this repository covers the issue. Maybe i should add this to the faq to.

**Comment by jonbp** [comment]
Thanks for your reply,
In this case it was me not reading the documentation well enough, next time I won't be so quick to open an issue.
