### ISSUE TITLE
Make all image sizes availible

### ISSUE THREAD

**Issue by benjibee** [vollyimnetz/crop-thumbnails#32]
I have enabled a hard crop for my `medium` and `large` image sizes via a custom theme. This plugin currently only shows the thumbnail and custom images, would it be possible to add the default image sizes if crop is enabled?

Thanks!

**Comment by vollyimnetz** [comment]
Could you give me your add_image_size code?

**Comment by benjibee** [comment]
````php
// medium
update_option('medium_size_w', 1440);
update_option('medium_size_h', 756);
add_image_size('medium', 1440, 756, true);

// large
update_option('large_size_w', 2880);
update_option('large_size_h', 1512);
add_image_size('large', 2880, 1512, true);

**Comment by vollyimnetz** [comment]
After some testing, the fastest way to archive what you want, is to add the following code to your functions.php / theme.
´´´
add_filter( 'crop_thumbnails_image_sizes', function($sizes) {
	$sizes['medium']['crop'] = 1;
        $sizes['large']['crop'] = 1;
	return $sizes;
});
´´´

But i have to warn you - this is not how the plugin is intended to work. Sideeffects may occure, i.e. with the wordpress srcset feature.
If you want to have a individual crop on the image, you should use the wordpress default image editor for cropping the original image (and all its subsets) or add additional (custom) image sizes.
On the other hand its a brilliant idea, to make some of the default image-sizes a crop one.

Anyways, good luck.
P.S: Greating from the south of brandenburg ;)
