### ISSUE TITLE
Cache Busting improvement

### ISSUE THREAD

**Issue by codepuncher** [vollyimnetz/crop-thumbnails#34]
Hi @vollyimnetz,

Thanks for the great plugin, works great.

The only issue is that the cache busting technique being used is not reliable as query strings are easily ignored by a CDN (e.g. Cloudfront).

The best solution for this is to change the filename.
So instead of `https://distro-id.cloudfront.net/path/to/file-600x600.jpg?cacheBreak=1560349238553` you would have `https://distro-id.cloudfront.net/path/to/file-600x600_1560349238553.jpg`.

A more time-consuming solution would be to investigate support for plugins like WP Offload Media.

Is this something we can look into? Happy to help in any way.

Thanks!

CC: @TangRufus, @BufferOverNo, @JackAlexander1

**Comment by codepuncher** [comment]
Temporary workaround:

```php
add_filter('crop_thumbnails_filename', function ($filename, $file, $w, $h, $crop, $info): string {
    $dir          = $info['dirname'];
    $ext          = $info['extension'];
    $name         = wp_basename($file, '.'.$ext);
    $suffix       = $w.'x'.$h;
    $destfilename = $dir.'/'.$name.'-'.$suffix.'-'.time().'.'.$ext;
    return $destfilename;
}, 10, 6);
```

The code is copied from `\CptSaveThumbnail::generateFilename`, only change is that I add `'-'.time()` to the returned filename.

I see this being a worthwhile setting to add to the plugin as it would solve a lot of issues for those who use WP Offload Media (see: https://wordpress.org/support/topic/compatibility-with-wp-offload-media-from-deliciousbrains/), Cloudfront or other options.

**Comment by AtlantaJones** [comment]
@codepuncher Is this workaround still working out for you? We're having trouble with a site hosted on Pantheon, where it appears the CDN is holding onto the previous version of cropped images. 

My only concern about this workaround is how many orphaned previously-cropped images it might leave hanging out in the uploads folder.

**Comment by codepuncher** [comment]
This works fine still for me @AtlantaJones.
Our files are deleted from the server once uploaded to the CDN. When regenerating or cropping thumbnails, the files are downloaded from the CDN and new version is uploaded.

**Comment by TangRufus** [comment]
> My only concern about this workaround is how many orphaned previously-cropped images it might leave hanging out in the uploads folder.

> Our files are deleted from the server once uploaded to the CDN. When regenerating or cropping thumbnails, the files are downloaded from the CDN and new version is uploaded.

It depends on how your "offload plugin" works. 
The plugin @codepuncher refering to is [wp offload media](https://aff.deliciousbrains.com/idevaffiliate.php?id=21242&url=34&tid1=github&tid2=https%3A%2F%2Fgithub.com%2Fvollyimnetz%2Fcrop-thumbnails%2Fissues%2F34).

**Comment by AtlantaJones** [comment]
@codepuncher I implemented your function and it worked great for saving a timestamped filename. But with each crop, the files just kept building up. So I added this bit before returning the new filename:

```php
  // delete previous version(s) of
  // this crop for this image
  $thisFile     = $info['filename'].'-'.$suffix;
  $files = scandir($dir);
  foreach ($files as $file) {
    if (strpos($file, $thisFile) !== false) {
      // file found. Delete it
      unlink($dir.'/'.$file);
    }
  }
```
All it does is take the base name, and the dimensions (ie, test-1280x720) and looks for matching files.

And while this works, I've noticed one other quirk. In the crop tool interface, once you crop the image and hit "save", the thumbnails of the images affected refresh and are broken, as they're trying to load the previous filename. Not sure why it wouldn't be retrieving the filename of the images it just saved. 

It's not a deal-breaker, as I can just tell the client they'll have to re-open the interface to crop again. But thought I'd bring it up here.

**Comment by vollyimnetz** [comment]
hi @AtlantaJones,
the "quirk" you noticed may be a bug that i just fixed. WordPress 5.3 optimized some parts of the image generation. Now the largest image called "imagename-scaled.ext". My plugin was not adjusted to that so all new thumbnails where called "imagename-scaled-150x150.ext" instead of "imagename-150x150.ext".
I fixed this behavior in the last commit - will be shipped with version 1.2.6. (approximately in the next 48 hours). You may try the changes.

**Please notice** to fix this i had to adjust the "crop_thumbnails_filename" filter. There is now an additional parameter.

**Comment by AtlantaJones** [comment]
That's fantastic! Can't wait to try it out in the update.

**Comment by AtlantaJones** [comment]
So I updated the plugin this morning, and made sure my WP was updated (to 5.3.1). On crop and save, I'm getting ajax errors, where the server was responding with a 500. 

Here is a stripped down version of my code:

```php
add_filter('crop_thumbnails_filename', 'aub_rename_cropped_thumbnails', 10, 6);

function aub_rename_cropped_thumbnails ($destfilename, $file, $w, $h, $crop, $info, $imageMetadata) {
  return $destfilename;
}
```
And my WP debug log is throwing this error:
```log
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function aub_rename_cropped_thumbnails(), 6 passed in /app/wp-includes/class-wp-hook.php on line 290 and exactly 7 expected in /app/wp-content/themes/auburn-cadc/lib/images.php:8
```
Not sure what's happening here, as it looks as if 7 arguments are passed from `save.php` on line 345. Any ideas?

**Comment by vollyimnetz** [comment]
Thats why i made the notice about the additional parameter.
You need to change your function call (add_filter).
```
add_filter('crop_thumbnails_filename', 'aub_rename_cropped_thumbnails', 10, 7);
```
The number in the end of the add_filter call defines how much parameters the function uses.

**Comment by AtlantaJones** [comment]
Ah, sorry, no idea how I didn't catch that. 

Still, when I save a crop, the thumbnails refresh and are trying to load the previous version of the image I just deleted.

**Comment by AtlantaJones** [comment]
Full version of my code here:
```php
add_filter('crop_thumbnails_filename', 'aub_rename_cropped_thumbnails', 10, 7);

function aub_rename_cropped_thumbnails ($destfilename, $file, $w, $h, $crop, $info, $imageMetadata) {
  $dir          = $info['dirname'];
  $ext          = $info['extension'];
  $name         = wp_basename($file, '.'.$ext);
  $suffix       = $w.'x'.$h;
  $destfilename = $dir.'/'.$name.'-'.$suffix.'-'.time().'.'.$ext;
  $thisFile     = $info['filename'].'-'.$suffix;

  // delete previous version(s) of
  // this crop for this image
  $files = scandir($dir);
  foreach ($files as $file) {
    if (strpos($file, $thisFile) !== false) {
      // file found. Delete it
      unlink($dir.'/'.$file);
    }
  }
  return $destfilename;
}
```

**Comment by vollyimnetz** [comment]
You may check if the metadata with the new filename is correctly stored in the database.
```
select * from postmeta m where m.post_id = <your-image-id>
```

**Comment by AtlantaJones** [comment]
Yeah, it's in the DB. When I save a new crop, if I look at the post on the front end, it's loading the proper image. When I close the crop dialog and open it back up, it's also correct. So it seems, at least on my end, that whatever is reloading the thumbnail after cropping just isn't finding the new filename. I'm just not sure where in the plugin that's happening.

**Comment by AtlantaJones** [comment]
Just checking in on this after the holidays. Like I said, based on my custom code, everything is mostly working great. The cropped files are saving with new filenames and the old versions deleted. But after the crop, the new image isn't refreshing in the tool. If you close and reopen it's fine. 

I've been looking through the plugin code and it seems like maybe the variable `changedImageName` isn't getting returned in the ajax call. Only `success`. Just wondering why somehow it's not detecting that the filename is different.

**Comment by vollyimnetz** [comment]
Hi i am not sure if the plugin really returns an imagename - cause in my (the normal) usecase its not needed (the imagenames do not change - i reload by adding a cache-break-parameter).

**Comment by AtlantaJones** [comment]
Gotcha. Honestly, I think it's such a small issue that we're probably fine with it. Thanks!

**Comment by ethanclevenger91** [comment]
I don't love the idea of renaming, since won't this mess up existing post content?

Specifically looking into WP Offload Media compatibility right now. I thought the new crop wasn't being offloaded, but it is. It just needs re-versioned. Other plugins do it, so I'm verifying w/ the Delicious Brains team how you accomplish that.
