### ISSUE TITLE
Image crop on options page

### ISSUE THREAD

**Issue by thatvideowebguy** [vollyimnetz/crop-thumbnails#36]
Hi there, 
first thanks for this great plugin, 
I just need to activate crop thumbnail button on a option page, 
I can see the button but the button is'nt active.
I tried the filter from documentation 
add_filter('crop_thumbnails_activat_on_adminpages', function($oldValue) {
	global $pagenow;
	return $oldValue || $pagenow==='admin.php?page=theme-general-settings';
	//for adding taxonomy edit-page to the list of pages where crop-thumbnails work
});

but no result, 
can you help me on this ?
thanks
Regards

**Comment by vollyimnetz** [comment]
Hi,
it seems wordpress changed the way it serves it admin-pages.
Try to add the following code to get the correct page:
```
add_filter('crop_thumbnails_activat_on_adminpages', function($oldValue) {
	global $pagenow;
	echo '<h1><center>---'.$pagenow.'---</center></h1>';
	return $oldValue || $pagenow==='admin.php?page=theme-general-settings';
});
```
Navigate to the page you like to add the crop-thumbnails functionality.
Replace the value that is compared with $pagenow with the value you see on the page, and remove the output line.

**Comment by thatvideowebguy** [comment]
Thanks for your quick answer 
I tried your code, but it's not working for now, 
I have an output : -- admin.php ---
So i tried to add $ pagenow === 'admin.php' , and it works, but, may be bad to activate this function on all admin page right ?

**Comment by vollyimnetz** [comment]
What wordpress version do you running?

**Comment by thatvideowebguy** [comment]
Latest releaseQ-------- Message original --------Objet : Re: [vollyimnetz/crop-thumbnails] Image crop on options page (#36)De : vollyimnetz À : vollyimnetz/crop-thumbnails Cc : thatvideowebguy ,Author What wordpress version do you running?

**Comment by vollyimnetz** [comment]
I am running WP Version 5.2.3 - and i got a different value of $pagenow on every settings-page in the backend.

**Comment by thatvideowebguy** [comment]
I'm using this wordpress version too, 
fyi, this my code for the option page, i'm using ACF to achieve that, 
```
<?php 
add_action('acf/init', 'my_acf_init');

function my_acf_init() {
	
	if( function_exists('acf_add_options_page') ) {
		
		$option_page = acf_add_options_page(array(
			'page_title' 	=> __('Theme General Settings', 'my_text_domain'),
			'menu_title' 	=> __('Theme Settings', 'my_text_domain'),
			'menu_slug' 	=> 'theme-general-settings',
		));
		
	}
	
}
?> 
```
