### ISSUE TITLE
Typo "wordpress"

### ISSUE THREAD

**Issue by waviaei** [vollyimnetz/crop-thumbnails#38]
`Not yet cropped by wordpress`
should be
`Not yet cropped by WordPress`

https://github.com/vollyimnetz/crop-thumbnails/blob/c4a41b9deaa11e74336ecea73ba25fe36e7e14f9/functions/editor.php#L79

**Comment by vollyimnetz** [comment]
Thank you, will be fixed in the upcoming version.
