### ISSUE TITLE
Lost crop when regenerate

### ISSUE THREAD

**Issue by fcharrasse** [vollyimnetz/crop-thumbnails#39]
Hello

Thanks for the great plugin !
I use https://fr.wordpress.org/plugins/force-regenerate-thumbnails/ and when images are regenerate, the croped images are reset to defaut wordpress crop (center).

Is it possible to keep the croped images intact ?

Thank you.

**Comment by vollyimnetz** [comment]
That depends on the regenerate-plugin - since one of the last versions i store the crop date inside the media-postmetadata so if the plugin supports a regeneration it has to use that data.

By

**Comment by smeedijzer-internet** [comment]
Which regenerate-plugin does that?

**Comment by fcharrasse** [comment]
> 
> 
> Which regenerate-plugin does that?

The link of the plugin is in my first message.

**Comment by vollyimnetz** [comment]
> Which regenerate-plugin does that?

I do not know of any regenerate-plugin that take my plugin into account.

**Comment by smeedijzer-internet** [comment]
Thanks for answering, I hoped it already existed
