### ISSUE TITLE
Webp-Express and Crop-thumbnails

### ISSUE THREAD

**Issue by bonakor** [vollyimnetz/crop-thumbnails#48]
Hello, 
[Someone](https://wordpress.org/support/topic/crop-thumbnails-and-webp-express/) in the Support page of WebpExpress proposed to add these line to /save.php, to make it compatible with WebP.
`if(file_exists($currentFilePath . “.webp”)){
unlink($currentFilePath . “.webp”);
}` after line 73 of the save.php

I wanted to know what you think and if you had maybe a better idea to make your plugin compatible with WebP-Express.

Thank you :)

**Comment by vollyimnetz** [comment]
Hi @bonakor thank you for give me a note about this.
For the new version 1.3 i had a look into webp-express myself (i think i want to add the plugin to my normal tool-stack).
I think webp-express had changed the way they generate the webp-files since then. They now save the webp-images in a separate folder. Also it seems they use a direct filter whenever a file is cropped to update the webp-image.
So i think to further code is needed. At least i dont need no further code when testing version 1.3 of crop-thumbnails.

**Comment by domaze** [comment]
Hello @vollyimnetz, hello @bonakor,

On my side I still have the problem on Wordpress. I use :
 - Webp Express version 0.17.2. 
 - Crop Thumbnails version 1.3.0 
 When Webp Express is activated, Crop Thumbnails works fine but when Webp Express it does not work any more. 
Activating debug mode give no clue (completely silent about this problem : no notice, no warning, no message at all)
 Applying @bonakor patch at line 73 doe not solve anything for me. Could you give me some help?
 
 Thank you :)

**Comment by domaze** [comment]
Hello @vollyimnetz, hello @bonakor,

In fact @bonakor is OK. Sorry I made a beginner's mistake. Never mind. Thank you for this nice plugin!

**Comment by bonakor** [comment]
Yeah, I agree! Thanks for having a look.

**Comment by bonakor** [comment]
In fact, I think it's not solved yet.

**Comment by vollyimnetz** [comment]
Its not an good idea for crop-thumbnails to clean the cache of another plugin. The other image needs to be notified that a change has happend. I will have a look into that.

**Comment by vollyimnetz** [comment]
https://github.com/rosell-dk/webp-express/issues/486

**Comment by vollyimnetz** [comment]
#rosell-dk/webp-express/issues/486

**Comment by benjibee** [comment]
Hey @bonakor is this issue solved by WP 5.8 and native support for WebP thumbnail generation? A PR of mine (#54) was just merged that adds support for WP's native WebP (AVIF, etc.) support. Maybe have a look!

**Comment by phscam** [comment]
For anyone that is looking for a quick fix:

As it depends on the configuration of WebPExpress where webp images are saved it's hard to delete the webp file. However, you can trigger a 'manual' conversion of the newly created crop.

```php
class Hooks
{
    public function __construct()
    {
        $this->actions();
    }

    public function actions()
    {
        add_action('crop_thumbnails_after_save_new_thumb', [$this, 'convert_webp_for_new_crop'], 100);
    }


    /** 
     * Trigger new Webp conversion for new image crop.
     */
    public function convert_webp_for_new_crop($new_crop)
    {
        if (class_exists(\WebPExpress\Convert::class)) {
            // convertFile internally loads the config of WebPExpress and converts the specified file.
            // we can can call this method because at 'crop_thumbnails_after_save_new_thumb' the new crop is already saved to uploads.
            \WebPExpress\Convert::convertFile($new_crop);
        }
    }
}
```

For us it does exactly what we want: update the webp file of a newly cropped image :)

**Comment by pbov** [comment]
@phscam this works for us, thanks!

I think this is a solution which can be integrated into @vollyimnetz great plugin.

**Comment by vollyimnetz** [comment]
Will be in 1.5.0
