### ISSUE TITLE
The plugin doesn't replace the old crop sizes when the crop is done on a different month than the original upload

### ISSUE THREAD

**Issue by bonakor** [vollyimnetz/crop-thumbnails#52]
Hi.

I think I've found an issue.

On one of the website I developped, an editor published a post with a featured image yesterday (May 31st).

Today (June 1st) when I crop the image, the plugin doesn't replace the original image.

I think that's because the original image was posted in May and the crops take place in JUne, so the folder is not the correct one.

Because I tried to upload the image again today and the crops worked without issue.

What do you think?

**Comment by vollyimnetz** [comment]
I just tested this on one of my websites:
- Post was created on 20.04.2021
- Featured Image was Uploaded in "uploads/2021/04/"
- I recropped the image
- the cropped image was on the exact same location as it was before (it was updated - as intended)
