### ISSUE TITLE
Thumbnail generation fails if replacement MIME-type specified for sub-sizes

### ISSUE THREAD

**Issue by benjibee** [vollyimnetz/crop-thumbnails#55]
Since WordPress 5.8 the image_editor_output_format hook makes it possible for generated thumbnails (sub-sizes) to be of a different image format than the original image. This is part of WordPress adding support for WebP, and eventually will also include other formats such as AVIF and JPEGXL.

This plugin currently fails silently and will not generate images if the MIME-type of the original image doesn't match that which is overridden by the `image_editor_output_format` hook.

**Comment by vollyimnetz** [comment]
You change will be included in Version 1.4.0.
