### ISSUE TITLE
Incorrect crop area saved when original image is larger than 2560

### ISSUE THREAD

**Issue by kurtrank** [vollyimnetz/crop-thumbnails#74]
I found that I was having the same issue that was reported here https://wordpress.org/support/topic/saved-the-wrong-cropped-area/ where the actual crop does not match the editor. Upon further experimentation I discovered that it only happens when super large images with dimensions above 2650 are uploaded. I guess it's related to [WordPress scaling them down starting in 5.3](https://make.wordpress.org/core/2019/10/09/introducing-handling-of-big-images-in-wordpress-5-3/) although I think that feature may have changed since then. I did not find anything in releases after 5.3 talking about that feature, but I did not see any "-scaled" image being created for new images I am testing with.

Either way, it is only a problem for images larger than 2560. I came across this when registering additional image sizes so that I can upload one big image and only output different crop sizes on the frontend where needed. Here is a test image much larger than 2560 to demonstrate. The full image dimensions are listed in the inspector, and in the crop editor they are listed as 2560x1707:

<img width="1194" alt="Screen Shot 2023-03-20 at 11 53 53 AM" src="https://user-images.githubusercontent.com/11091840/226396287-28bcc259-7a00-4c44-8952-5349376354ae.png">

**Comment by vollyimnetz** [comment]
Hi @kurtrank,
thanks for reporting. Can you please

- provide me the original image?
- provide me the log of the plugin-test on that site (Settings -> Crop-Thumbnail -> Plugin Test)

**Comment by kurtrank** [comment]
Hey, thanks for the info. Here is the image I tested with: https://www.pexels.com/photo/photo-of-a-person-holding-an-umbrella-940034/. I downloaded it straight from there and did not do any editing or adjusting to it.

And here is the log from the plugin test:

```
info Crop-Thumbnails 1.4.0
info PHP 7.4.30
info PHP memory limit 256M
info WP_Image_Editor_GD (choosed Wordpress imageeditor class for jpg)
success Temporary directory exists
success Copy testfile to temporary directory
success Testfile was successfully added to media-library. (ID:2096)
success Cropping the file
success Cropped image dimensions are correct.
success Test-attachement successfull deleted (ID:2096)
success Remove testfile from temporary directory
info Tests complete
```

Yes this local site I am testing with has PHP 7.4 and it is a different image editor class, so could be related to that. I am not too familiar with the different image editing modules, but I can try to upgrade PHP and/or try to get it to use Imagick instead.

**Comment by kurtrank** [comment]
I did some more testing yesterday, including disabling all other plugins, switching PHP versions and editors but the issue still remained. I just did some more testing today based on the information you provided and I think I have found the problem. You are right, it is another plugin that messes with the file generation.

I tried uploading the same photo to a second test site and cropping works perfectly. I noticed a difference in that my new test site made a '-scaled' file of the image (to fit 2560px), but my original test site is missing that '-scaled' file in the uploads folder. I made sure all plugins were still disabled and tried uploading the image a second time to the first site and this time the scaled version was made correctly. Here is my uploads directory with a scaled copy for the second upload, but missing from the first.

<img width="741" alt="Screen Shot 2023-03-29 at 3 32 12 PM" src="https://user-images.githubusercontent.com/11091840/228647974-07a9d8c9-23a4-410b-a119-e8f0efe4989d.png">

I checked the meta for the attachment saved in the database and found for my original image that the width, height, filesize were listed for the "scaled" version, but the filesize actually pointed to the original image.

### Image that doesn't work

```
Array
(

    // this is the width of the scaled file, the original is actually 5367
    [width] => 2560
    [height] => 1707

     // `-scaled` is missing from the filename
    [file] => 2023/03/pexels-andrey-grushnikov-940034.jpg
    [filesize] => 890443 // this filesize is also for the scaled version
    [sizes] => Array
        (
            [medium] => Array
                (
                    [file] => pexels-andrey-grushnikov-940034-300x200.jpg
                    [width] => 300
                    [height] => 200
                    [mime-type] => image/jpeg
                    [filesize] => 18065
                )
            // other sizes...
        )
)
```

### Reuploaded working image

```
Array
(
    [width] => 2560
    [height] => 1707
    [file] => 2023/03/pexels-andrey-grushnikov-940034-2-scaled.jpg
    [filesize] => 890443
    [sizes] => Array
        (
            [medium] => Array
                (
                    [file] => pexels-andrey-grushnikov-940034-2-300x200.jpg
                    [width] => 300
                    [height] => 200
                    [mime-type] => image/jpeg
                    [filesize] => 18065
                )
            // other sizes...
        )
)
```

I guess because WordPress saved the size as being 2560x1707, the crop is set based on those dimensions but the actual file does not match and is much bigger than 2560x1707 and therefore does not match the preview when cropping.

### Solution

I re-enabled plugins until I found **[Image Regenerate & Select Crop](https://wordpress.org/plugins/image-regenerate-select-crop/)** causes the `-scaled` image to be removed for some reason. It looks like it tries to get rid of that size, but I guess the metadata does not get updated correctly. It looks like I need to go file an issue there. I believe this would be a problem for any plugin that causes the meta and filename to get out of sync and not limited to this one plugin, but maybe it is possible [that original report](https://wordpress.org/support/topic/saved-the-wrong-cropped-area/) tried the same second plugin I had. I mainly used this other plugin because it shows in the admin a list of generated sizes and filesizes, which is helpful for our editors.

I didn't expect the existing image to still not work even with everything disabled, I wish I had thought to try reuploading the image sooner. So your plugin works great, looks like a problem with this other one. Not sure if there is anything to be done when the metadata is mismatched like that. Thank you for your assistance in looking into it, sorry for the trouble! I'll try to dig deeper on my own before posting an issue next time. Your plugin is really cool, it has made working with extra image sizes much more powerful and the UI is really nice!
