### ISSUE TITLE
Crop thumbnails is not working

### ISSUE THREAD

**Issue by tonyr10sam** [vollyimnetz/crop-thumbnails#80]
I have been using the crop thumbnails plugin in my WordPress website for more than 4 years now and it has been working fine. I noticed that the plugin has stopped working for more than 1 month now.

We are using the WP Offload Media plugin to offload our media files to an external AWS S3 bucket.
When I click the Crop Featured Image button, the popup shows the thumbnail versions in 3 different sizes but for some reason when I select one of the image sizes for cropping, it keeps on loading the preview on the right side of the screen and it never loads.

We are using the 1.7.2 version of the plugin.
Please note we are using the Regenerate thumbnails plugin too.

Please note that my site is hosted in a PHP 8.1 version, Elastic Beanstalk load-balanced environment in AWS.

Hoping for a quick resolution from your end. 

Thanks in advance,
Tony George Sam

**Comment by vollyimnetz** [comment]
Did you change anything in the setup in the last 2 Month? I do not recommend to use an CDN when working with the plugin, as the image file resaved with the same name.

You may try an older version of the plugin, but i would guess the problem is in the CDN workflow.

**Comment by tonyr10sam** [comment]
Thank you for the quick response. 
Yes, you are right, we started using CDN recently only. This was done based on the recommendation from the AWS team for TLS 1.2 enforcement. 
Is there anyway we can use this plugin in a CDN environment?

Thank you.

**Comment by vollyimnetz** [comment]
You have to reupload the image after the cropping has been done. You may use one of the hooks my plugin provided to do so.

Have a look on the file functions/extend/WebPExpressExtension.php
This is a extension i included to make the WebPExpress-Plugin work together with the crop-thumbnails-plugin. Its essentially the same problem. It has to perform a task, in your case the reupload of the image, after the crop has been done.

**Comment by tonyr10sam** [comment]
Thank you,
I tried installing the WebP Express plugin, but still the crop thumbnails plugin is working. I tried uploading a new image and it doesn't work.
Should I make any changes within the core files of the plugin?

**Comment by tonyr10sam** [comment]
Hi @vollyimnetz 
We disabled the CDN and still we are facing the issue. 
The thumbnails are listed but when I click on any of them, the loader keeps on spinning and error message saying "Original image size is too small for good crop quality" 
<img width="1326" alt="crop-thumbnails-ss" src="https://github.com/vollyimnetz/crop-thumbnails/assets/146129107/4c7325bf-ea50-4979-9904-420cec221174">

Please consider this a priority as we have been stuck with this issue for a long time. 
Thanks in advance

**Comment by jmarxuach** [comment]
I have the same issue with plugin WP Offload Media Lite. This plugin changes all image url from : 
`https://myWPSITE/wp-content/uploads/2023/11/myimage.jpeg`  to the s3 service  `https://s3domain/wp-content/uploads/2023/11/myimage.jpeg`  
I have the warning : 
`Access to XMLHttpRequest at 'https://s3domain/wp-content/uploads/2023/11/myimage.jpg' from origin 'https://myWPSITE' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

But i have as well the message : 
`Failed to load resource: the server responded with a status of 404 for https://myWPSITE/wp-content/uploads/2023/11/myimage.jpeg`

So, I think "Crop thumbnails" is not using s3domain urls.

**Comment by jmarxuach** [comment]
with WP Offload Media plugin, I had the warning. We modify CORS policy of our s3 and solve the issue: 

> "Access to XMLHttpRequest at 'https://mydomain/wp-content/uploads/2024/11/myimage.jpg' from origin 'https://mydomain/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."
