### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ridesirat** [vollyimnetz/crop-thumbnails#91]
Hi Volkmar

I'm never tired to flatter your plugin. Just great!

Not sure if you are open to suggestions, but here they go..

**1.**
For performance optimization, I think it would be helpful if we could lock the option "Group together" for the user, in the "Images with same ratio", when we want to. This way we would be sure that the client cropps all the images for the different src sizes we need.

As a solution, maybe adding image sizes with the same name but with an -2, -4, ... added to it? i.e:
add_image_size( 'Clipping', 0, 200, true );
add_image_size( 'Clipping-2', 0, 400, true );
add_image_size( 'Clipping-4', 0, 800, true );

and the behaviour in the crop would change.

**2.**
It would be nice to have a switcher in the Options to, instead of "Choose the image sizes you do not want to show", it would do the opposite: "Choose the image sizes you want to show".
It seems easier to organize and to maintain as we don't have to update all of them if we create a new image size.
And each user could chose how it would prefer.

Once again, thanks for the great plugin!

**Comment by vollyimnetz** [comment]
Hi @ridesirat,
thank you for your feedback.

about (1) - i liked the idea to lock the group together option. But i used i simpler solution. I added an additional option on the settings page, to always use a certain "same ratio rule". Note that this is true for all users on all images. I hope that this is something you could work with.

about (2) - the reason this is done that way is, that the plugin should be beginner friendly. If i hide all image sizes in the beginning, than no one could crop any image.
