### ISSUE TITLE
compatilibity with Modern Image Formats

### ISSUE THREAD

**Issue by 1ucay** [vollyimnetz/crop-thumbnails#92]
Hi, I like AVIF format with plugin https://wordpress.org/plugins/webp-uploads/
Plugin can convert jpg files to webp or avif on local server and serve picture html element with source tag with jpg fallback.
Plugin is minimal ( only some settings in Settings -> Media ) and in maintained by WP performance team.

But with your plugin not working. If I crop image, cropping jpg is ok, but AVIF image is same.

Thank you.

**Comment by vollyimnetz** [comment]
Hi @1ucay i didn't notice that wordpress already supports the avif format. (https://make.wordpress.org/core/2024/02/23/wordpress-6-5-adds-avif-support/)
I will have a look on it. So long i could recommend the "WebP Express" Plugin.

**Comment by vollyimnetz** [comment]
@1ucay 
* got to functions\backendpreparer.php
* change the file 9 as follows:

`protected $allowedMime = ['image/avif','image/webp','image/jpeg','image/png'];`

This change will be in the next release of the plugin.

**Comment by vollyimnetz** [comment]
New version is now live. If your server is able to process avif files it should be working now.
