### ISSUE TITLE
Crop uses the "-scaled" image

### ISSUE THREAD

**Issue by Arcath** [vollyimnetz/crop-thumbnails#94]
We've uploaded some large images that wordpress has re-sized to a "-scaled.jpg" and only offers that. The media library does have a link to the original image but is using the scaled.

The scaled is too small for some of the horizontal banners we'd like to crop. The idea being we have a native 4k/1440p/1080p version of the same header. 

Is it possible to use the original image for cropping? then it would be wide enough.

**Comment by vollyimnetz** [comment]
Hi @Arcath, thank you for your feedback.

I can dimly remember that I designed the programming back then (about 3 years ago) so that PHP would not crash when trying to crop the image with the original uncropped image size.

I will have a deeper look into the problem.

**Comment by vollyimnetz** [comment]
@Arcath A quick tip while researching. Seems you can disable the scaling of the original image. I guess this would fix your problem too.

https://smartwp.com/large-image-scaling-wordpress/

**Comment by vollyimnetz** [comment]
The more I think about it, the more I believe that this is the solution for your problem:
As your image-size-settings are larger than the default setting for the scaling, you need to increase it. This would lead to wordpress not even generate scaled versions. But be aware that this would lead to increased memory usage on any image-operation.
```
add_filter( 'big_image_size_threshold', function($threshold) {
    return 4096;
}, 999, 1);
```
