### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by 1ucay** [vollyimnetz/crop-thumbnails#99]
There is missing third parameter mime_type
crop-thumbnails/functions/save.php(420)
https://developer.wordpress.org/reference/hooks/image_editor_output_format/

   [12-Nov-2024 09:22:28 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function webp_uploads_filter_image_editor_output_format(), 2 passed in /data/.........../wp/wp-includes/class-wp-hook.php on line 324 and exactly 3 expected in /data/.........../app/plugins/webp-uploads/hooks.php:318
    Stack trace:
    #0 /data/.........../wp/wp-includes/class-wp-hook.php(324): webp_uploads_filter_image_editor_output_format(Array, '/data/f/2/f2548...')
    #1 /data/.........../wp/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
    #2 /data/.........../app/plugins/crop-thumbnails/functions/save.php(420): apply_filters('image_editor_ou...', Array, '/data/f/2/f2548...')
    #3 /data/.........../app/plugins/crop-thumbnails/functions/save.php(83): crop_thumbnails\CptSaveThumbnail::generateFilename('/data/f/2/f2548...', Array, 768, 768, 1)
    #4 /data/.........../wp/wp-includes/rest-api/class-wp-rest-server.php(1230): crop_thumbnails\CptSaveThumbnail::saveThumbnail(Object(WP_REST_Request))
    #5 /data/.........../wp/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/crop_thumbnail...', Array, NULL)
    #6 /data/.........../wp/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
    #7 /data/.........../wp/wp-includes/rest-api.php(420): WP_REST_Server->serve_request('/crop_thumbnail...')
    #8 /data/.........../wp/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
    #9 /data/.........../wp/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
    #10 /data/.........../wp/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
    #11 /data/.........../wp/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
    #12 /data/.........../wp/wp-includes/class-wp.php(813): WP->parse_request('')
    #13 /data/.........../wp/wp-includes/functions.php(1336): WP->main('')
    #14 /data/.........../wp/wp-blog-header.php(16): wp()
    #15 /data/............/index.php(6): require('/data/f/2/f2548...')

**Comment by vollyimnetz** [comment]
Hi @1ucay, can you please test if the current master fixes your problem? Should be enough to replace "crop-thumbnails\functions\save.php".

**Comment by vollyimnetz** [comment]
Live in version 1.9.5
